version: "3"

services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: mrb-php
        volumes:
            - ./src:/var/www/html/
        ports:
            - "80:80"
            - "443:443"
        links:
            - mongo

    mongo:
        image: mongo:4.2
        container_name: mrb-mongodb
        restart: always
        ports:
            - 27017:27017
        #environment:
        #MONGO_INITDB_ROOT_USERNAME: root
        #MONGO_INITDB_ROOT_PASSWORD: root
